name: inf
version: '1.0-SNAPSHOT'
main: com.Inf
api-version: '1.21'
folia-supported: true

commands:
  playerdata:
    description: "玩家数据保存/加载"
    usage: /playerdata <save|load|list|reload> [player]
    aliases:
      - playerdata
  #backup:
    #description: "手动备份所有世界"
    #aliases:
      #- backup
      #- bk